language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
      secure: cxq1c0kK0cq4un4lFaLSJyh4Gh5vnj0NPFszBOYETWI/pGD4hFLSxLMccVZoNP5sQE82+lvcvtxn+O0j2JNvtTKdyBzReJNz25a/3moKYC9O6WY3M/6ZTbMGk8xMsfl6dRlq6tyriZeUBkCXBtLCWW3vvkGzeg67eEXRDd9oIF8=
  app: k02-hubot

